language: node_js
node_js:
  - "10.15.3"
cache:
  directories:
  - node_modules
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 192927f1c3c754da0f12dfd1eaef204ca3e00e61
  keep_history: true
  on:
    branch: master