language: node_js
node_js:
  - "10.15.3"
cache:
  directories:
  - node_modules
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  keep_history: true
  local_dir: build
  on:
    branch: master